export const defaultInternalLayoutOptions = {
  width: 1000,
  height: 1000,
  rootLength: 0,
  rootAngle: 0,
  angleRange: 2 * Math.PI - 0.3,
  tipSpace: () => 1,
  curvature: 0,
  showRoot: false,
  spread: 1,
  fishEye: { x: 0, y: 0, scale: 0 },
  cartoonedNodes: new Map(),
  pollard: 0,
  padding: 20,
  invert: false,
  minRadius: 0,
};
